import { DriverProfile, RecruiterProfile, JobPosting, JobApplication, MasterData } from '../types';

export const INITIAL_MASTER_DATA: MasterData = {
  endorsementTypes: [
    'HazMat (H)',
    'Tanker (N)',
    'Doubles/Triples (T)',
    'Combination HazMat + Tanker (X)',
    'Passenger (P)',
    'TWIC Card',
    'TSA PreCheck / FAST Card',
  ],
  equipmentTypes: [
    'Dry Van',
    'Refrigerated (Reefer)',
    'Flatbed / Step Deck',
    'Tanker (Liquid / Chemical)',
    'Auto Hauler',
    'Intermodal / Container',
    'Heavy Haul / Lowboy',
    'Box Truck / Straight Truck',
  ],
  routeTypes: [
    'Over-The-Road (OTR)',
    'Regional (Home Weekly)',
    'Local (Home Daily)',
    'Dedicated Route',
  ],
  regions: [
    'National (Lower 48)',
    'Midwest',
    'Southeast',
    'Northeast',
    'Southwest',
    'West Coast / Pacific',
    'Texas Regional',
    'Rocky Mountain',
  ],
};

export const SAMPLE_DRIVERS: DriverProfile[] = [
  {
    id: 'driver-john-reynolds',
    userId: 'user-driver-john',
    fullName: 'John "Mack" Reynolds',
    email: 'john.reynolds@trucklink.demo',
    phone: '(555) 234-8901',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46204',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    cdlClass: 'Class A',
    cdlNumber: 'IN-CDL-8829104A',
    cdlState: 'Indiana',
    cdlExpirationDate: '2028-11-15',
    endorsements: ['HazMat (H)', 'Tanker (N)', 'Doubles/Triples (T)', 'TWIC Card'],
    experienceYears: 7,
    cleanMvr: true,
    mvrViolationsCount: 0,
    equipmentTypes: ['Dry Van', 'Refrigerated (Reefer)', 'Flatbed / Step Deck'],
    preferredRoutes: ['Over-The-Road (OTR)', 'Regional (Home Weekly)', 'Dedicated Route'],
    availability: 'immediate',
    targetPayPerMile: 0.72,
    targetWeeklyGross: 2100,
    bio: 'Safety-focused Class A driver with 7+ years of accident-free OTR and regional reefer freight experience. 100% on-time delivery record with clean FMCSA Clearinghouse and current TWIC card.',
    documents: [
      {
        id: 'doc-1',
        name: 'Commercial Driver License (Class A)',
        type: 'cdl_front',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-10T14:30:00Z',
        expirationDate: '2028-11-15',
        verified: true,
      },
      {
        id: 'doc-2',
        name: 'DOT Medical Examiner Certificate',
        type: 'dot_medical',
        url: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-10T14:32:00Z',
        expirationDate: '2027-08-20',
        verified: true,
      },
      {
        id: 'doc-3',
        name: 'Official 3-Year MVR Driving Abstract',
        type: 'mvr',
        url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-10T14:35:00Z',
        verified: true,
      },
    ],
    status: 'approved',
    statusHistory: [
      {
        status: 'pending',
        timestamp: '2026-08-10T14:40:00Z',
        changedBy: 'user-driver-john',
        note: 'Submitted profile and documents for moderation review',
      },
      {
        status: 'approved',
        timestamp: '2026-08-11T09:15:00Z',
        changedBy: 'admin-marcus',
        adminName: 'Marcus Vance (Admin)',
        note: 'CDL Class A and DOT Medical Card verified. Clean MVR checked. Profile approved for recruiter matching.',
      },
    ],
    adminFeedback: 'Excellent driving record and complete credential package verified.',
    moderatedAt: '2026-08-11T09:15:00Z',
    moderatedBy: 'Marcus Vance',
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-08-11T09:15:00Z',
  },
  {
    id: 'driver-elena-rostova',
    userId: 'user-driver-elena',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@trucklink.demo',
    phone: '(555) 781-4420',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43215',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    cdlClass: 'Class A',
    cdlNumber: 'OH-CDL-9941029B',
    cdlState: 'Ohio',
    cdlExpirationDate: '2027-06-30',
    endorsements: ['Doubles/Triples (T)', 'Tanker (N)', 'TWIC Card'],
    experienceYears: 4,
    cleanMvr: true,
    mvrViolationsCount: 0,
    equipmentTypes: ['Refrigerated (Reefer)', 'Dry Van'],
    preferredRoutes: ['Regional (Home Weekly)', 'Over-The-Road (OTR)'],
    availability: 'two_weeks',
    targetPayPerMile: 0.70,
    targetWeeklyGross: 1950,
    bio: 'Dedicated refrigerated freight specialist with 4 years regional hauling across Midwest & Northeast corridors. Punctual, proficient with Thermo King & Carrier units.',
    documents: [
      {
        id: 'doc-elena-1',
        name: 'CDL Class A License Scan',
        type: 'cdl_front',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-19T10:15:00Z',
        expirationDate: '2027-06-30',
        verified: false,
      },
      {
        id: 'doc-elena-2',
        name: 'DOT Medical Examination Certificate',
        type: 'dot_medical',
        url: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-19T10:18:00Z',
        expirationDate: '2027-05-12',
        verified: false,
      },
    ],
    status: 'pending',
    statusHistory: [
      {
        status: 'pending',
        timestamp: '2026-08-19T10:20:00Z',
        changedBy: 'user-driver-elena',
        note: 'Submitted profile & uploaded Class A credentials for admin review.',
      },
    ],
    createdAt: '2026-08-19T09:45:00Z',
    updatedAt: '2026-08-19T10:20:00Z',
  },
  {
    id: 'driver-marcus-washington',
    userId: 'user-driver-marcus',
    fullName: 'Marcus Washington',
    email: 'm.washington@trucklink.demo',
    phone: '(555) 912-3344',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30303',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    cdlClass: 'Class A',
    cdlNumber: 'GA-CDL-4109823C',
    cdlState: 'Georgia',
    cdlExpirationDate: '2029-01-20',
    endorsements: ['HazMat (H)', 'Tanker (N)'],
    experienceYears: 5,
    cleanMvr: true,
    mvrViolationsCount: 0,
    equipmentTypes: ['Tanker (Liquid / Chemical)', 'Dry Van'],
    preferredRoutes: ['Regional (Home Weekly)', 'Dedicated Route'],
    availability: 'immediate',
    targetPayPerMile: 0.78,
    targetWeeklyGross: 2300,
    bio: 'Liquid bulk and chemical hauler with 5 years experience across Southeast routes. HazMat certified.',
    documents: [
      {
        id: 'doc-marcus-1',
        name: 'Commercial Driver License',
        type: 'cdl_front',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-18T16:00:00Z',
        expirationDate: '2029-01-20',
        verified: true,
      },
      {
        id: 'doc-marcus-2',
        name: 'DOT Medical Card (Blurry)',
        type: 'dot_medical',
        url: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-18T16:05:00Z',
        expirationDate: '2026-09-01',
        verified: false,
      },
    ],
    status: 'changes_requested',
    statusHistory: [
      {
        status: 'pending',
        timestamp: '2026-08-18T16:10:00Z',
        changedBy: 'user-driver-marcus',
        note: 'Initial submission',
      },
      {
        status: 'changes_requested',
        timestamp: '2026-08-19T08:30:00Z',
        changedBy: 'admin-marcus',
        adminName: 'Marcus Vance (Admin)',
        note: 'Please re-upload a high-resolution scan of your DOT Medical Card. The medical examiner registry number is cut off in the current photo.',
      },
    ],
    adminFeedback: 'Please re-upload a clear copy of your DOT Medical Card showing the Registry Number and expiration date.',
    moderatedAt: '2026-08-19T08:30:00Z',
    moderatedBy: 'Marcus Vance',
    createdAt: '2026-08-18T15:30:00Z',
    updatedAt: '2026-08-19T08:30:00Z',
  },
  {
    id: 'driver-tyler-vance',
    userId: 'user-driver-tyler',
    fullName: 'Tyler "Big Dog" Vance',
    email: 'tyler.vance@trucklink.demo',
    phone: '(555) 345-6712',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    cdlClass: 'Class A',
    cdlNumber: 'TX-CDL-5529188X',
    cdlState: 'Texas',
    cdlExpirationDate: '2028-09-10',
    endorsements: ['Combination HazMat + Tanker (X)', 'Doubles/Triples (T)', 'TWIC Card'],
    experienceYears: 10,
    cleanMvr: true,
    mvrViolationsCount: 0,
    equipmentTypes: ['Tanker (Liquid / Chemical)', 'Flatbed / Step Deck', 'Heavy Haul / Lowboy'],
    preferredRoutes: ['Over-The-Road (OTR)', 'Regional (Home Weekly)'],
    availability: 'immediate',
    targetPayPerMile: 0.85,
    targetWeeklyGross: 2600,
    bio: '10 years elite tanker and heavy-haul veteran. Extensive experience with cryogenics, petroleum products, and oversize heavy machinery.',
    documents: [
      {
        id: 'doc-tyler-1',
        name: 'CDL Class A with X Endorsement',
        type: 'cdl_front',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-05T11:00:00Z',
        expirationDate: '2028-09-10',
        verified: true,
      },
      {
        id: 'doc-tyler-2',
        name: 'DOT Medical Certificate',
        type: 'dot_medical',
        url: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-05T11:05:00Z',
        expirationDate: '2027-10-01',
        verified: true,
      },
    ],
    status: 'approved',
    statusHistory: [
      {
        status: 'pending',
        timestamp: '2026-08-05T11:15:00Z',
        changedBy: 'user-driver-tyler',
        note: 'Submitted profile',
      },
      {
        status: 'approved',
        timestamp: '2026-08-06T10:00:00Z',
        changedBy: 'admin-marcus',
        adminName: 'Marcus Vance (Admin)',
        note: 'Tanker endorsements and 10yr verified experience approved.',
      },
    ],
    adminFeedback: 'Master-level credentials verified.',
    moderatedAt: '2026-08-06T10:00:00Z',
    moderatedBy: 'Marcus Vance',
    createdAt: '2026-08-05T10:30:00Z',
    updatedAt: '2026-08-06T10:00:00Z',
  },
  {
    id: 'driver-carlos-hernandez',
    userId: 'user-driver-carlos',
    fullName: 'Carlos Hernandez',
    email: 'carlos.h@trucklink.demo',
    phone: '(555) 678-9012',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    cdlClass: 'Class B',
    cdlNumber: 'IL-CDL-1102948B',
    cdlState: 'Illinois',
    cdlExpirationDate: '2027-12-05',
    endorsements: ['Passenger (P)'],
    experienceYears: 3,
    cleanMvr: true,
    mvrViolationsCount: 0,
    equipmentTypes: ['Box Truck / Straight Truck', 'Dry Van'],
    preferredRoutes: ['Local (Home Daily)'],
    availability: 'immediate',
    targetPayPerMile: 0.60,
    targetWeeklyGross: 1600,
    bio: 'Class B city delivery professional. Expert navigating metropolitan tight docks, lift-gate operations, and daily route execution.',
    documents: [
      {
        id: 'doc-carlos-1',
        name: 'CDL Class B License',
        type: 'cdl_front',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
        uploadedAt: '2026-08-12T09:00:00Z',
        expirationDate: '2027-12-05',
        verified: true,
      },
    ],
    status: 'approved',
    statusHistory: [
      {
        status: 'pending',
        timestamp: '2026-08-12T09:10:00Z',
        changedBy: 'user-driver-carlos',
        note: 'Submitted',
      },
      {
        status: 'approved',
        timestamp: '2026-08-12T14:20:00Z',
        changedBy: 'admin-marcus',
        adminName: 'Marcus Vance (Admin)',
        note: 'Class B verified for metro home-daily positions.',
      },
    ],
    createdAt: '2026-08-12T08:30:00Z',
    updatedAt: '2026-08-12T14:20:00Z',
  },
  {
    id: 'driver-bradley-cooper',
    userId: 'user-driver-bradley',
    fullName: 'Bradley Cooper Jr.',
    email: 'bradley.c@trucklink.demo',
    phone: '(555) 432-1199',
    city: 'St. Louis',
    state: 'MO',
    zipCode: '63101',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    cdlClass: 'Class C',
    cdlNumber: 'MO-CDL-9029102C',
    cdlState: 'Missouri',
    cdlExpirationDate: '2025-12-01',
    endorsements: [],
    experienceYears: 0,
    cleanMvr: false,
    mvrViolationsCount: 3,
    equipmentTypes: ['Box Truck / Straight Truck'],
    preferredRoutes: ['Local (Home Daily)'],
    availability: 'flexible',
    targetPayPerMile: 0.45,
    targetWeeklyGross: 1100,
    bio: 'Looking for delivery helper and driving gigs.',
    documents: [],
    status: 'rejected',
    statusHistory: [
      {
        status: 'pending',
        timestamp: '2026-08-01T10:00:00Z',
        changedBy: 'user-driver-bradley',
        note: 'Submitted',
      },
      {
        status: 'rejected',
        timestamp: '2026-08-02T11:00:00Z',
        changedBy: 'admin-marcus',
        adminName: 'Marcus Vance (Admin)',
        note: 'Profile rejected: CDL license document was expired (12/2025) and multiple moving violations on driving abstract exceed commercial insurance limits.',
      },
    ],
    adminFeedback: 'License document expired and MVR records do not meet carrier underwriting criteria.',
    moderatedAt: '2026-08-02T11:00:00Z',
    moderatedBy: 'Marcus Vance',
    createdAt: '2026-08-01T09:30:00Z',
    updatedAt: '2026-08-02T11:00:00Z',
  },
];

export const SAMPLE_RECRUITERS: RecruiterProfile[] = [
  {
    id: 'recruiter-apex-freight',
    userId: 'user-recruiter-sarah',
    companyName: 'Apex Freight Logistics',
    dotNumber: 'USDOT 2891402',
    mcNumber: 'MC-940182',
    fleetSize: '250+ late model tractors',
    headquarters: 'Indianapolis, IN',
    contactName: 'Sarah Jenkins',
    contactEmail: 'sarah.jenkins@apexfreight.demo',
    contactPhone: '(317) 555-0199',
    website: 'https://apexfreight.demo',
    companyBio: 'Premier midwestern carrier specializing in dedicated temperature-controlled grocery distribution and dry van expedited freight. Modern 2024 Peterbilt & Freightliner fleet with APUs, invertors, and EpicVue satellite TV.',
    logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    verifiedAt: '2026-01-15T08:00:00Z',
    createdAt: '2026-01-10T12:00:00Z',
  },
  {
    id: 'recruiter-titan-tankers',
    userId: 'user-recruiter-dave',
    companyName: 'Titan Liquid Bulk & Tank Lines',
    dotNumber: 'USDOT 1948201',
    mcNumber: 'MC-610293',
    fleetSize: '85 chemical/fuel tankers',
    headquarters: 'Houston, TX',
    contactName: 'Dave Miller',
    contactEmail: 'dave.miller@titantankers.demo',
    contactPhone: '(713) 555-4920',
    website: 'https://titantankers.demo',
    companyBio: 'Leading hazardous materials and specialty bulk liquid transporter servicing Gulf Coast petrochemical hubs and national distribution corridors. Top industry pay with comprehensive safety bonuses.',
    logoUrl: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    verifiedAt: '2026-02-01T09:00:00Z',
    createdAt: '2026-01-28T14:00:00Z',
  },
];

export const SAMPLE_JOBS: JobPosting[] = [
  {
    id: 'job-apex-otr-reefer',
    recruiterId: 'recruiter-apex-freight',
    companyName: 'Apex Freight Logistics',
    title: 'OTR Reefer Dedicated Fleet Driver',
    description: 'Join our premier dedicated grocery network hauling fresh produce and frozen goods. Guaranteed weekly miles (2,800 - 3,200), brand new 2024 Freightliner Cascadia tractors equipped with automatic transmissions, microwave, refrigerator, and 2000W invertors.',
    routeType: 'Over-The-Road (OTR)',
    equipmentType: 'Refrigerated (Reefer)',
    cdlClassRequired: 'Class A',
    endorsementsRequired: ['TWIC Card'],
    minExperienceYears: 2,
    payDescription: '$0.72 - $0.76 CPM + $5,000 Sign-On Bonus + $100 Stop Pay',
    avgWeeklyPay: 2150,
    operatingRegions: ['Midwest', 'Southeast', 'National (Lower 48)'],
    benefits: [
      'Comprehensive BlueCross BlueShield Medical/Dental/Vision on Day 30',
      '401(k) with 100% company match up to 4%',
      'Rider & Pet Policy from Day 1',
      'Paid Orientation ($1,200) + Free Single Hotel Room',
      'Weekly Direct Deposit & Paid Detention after 1.5 hrs',
    ],
    status: 'active',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'job-titan-tanker-chemical',
    recruiterId: 'recruiter-titan-tankers',
    companyName: 'Titan Liquid Bulk & Tank Lines',
    title: 'Specialty Chemical & Liquid Tanker Driver',
    description: 'Immediate opening for experienced Class A liquid bulk drivers. Hauling dedicated chemical and industrial petroleum routes across Texas and Midwest. High earning potential with safety and loading incentives.',
    routeType: 'Regional (Home Weekly)',
    equipmentType: 'Tanker (Liquid / Chemical)',
    cdlClassRequired: 'Class A',
    endorsementsRequired: ['HazMat (H)', 'Tanker (N)', 'TWIC Card'],
    minExperienceYears: 3,
    payDescription: '$0.84 - $0.90 CPM + $40/hr Load/Unload Detention Pay',
    avgWeeklyPay: 2550,
    operatingRegions: ['Texas Regional', 'Midwest', 'Southwest'],
    benefits: [
      'Top Tier Premium Health, Dental & Prescription Plan',
      'Quarterly Safety & Fuel Mileage Bonus ($1,500/qtr)',
      '100% Company-Paid PPE, Boots & HazMat Endorsement Reimbursement',
      'Home Every Weekend Guaranteed 34-hour restart',
    ],
    status: 'active',
    createdAt: '2026-08-14T11:30:00Z',
    updatedAt: '2026-08-14T11:30:00Z',
  },
  {
    id: 'job-apex-regional-dryvan',
    recruiterId: 'recruiter-apex-freight',
    companyName: 'Apex Freight Logistics',
    title: 'Midwest Regional Dry Van - Home Weekends',
    description: 'No-touch freight dry van routes operating between Indiana, Ohio, Illinois, and Michigan. Consistent lanes with scheduled drop and hooks.',
    routeType: 'Regional (Home Weekly)',
    equipmentType: 'Dry Van',
    cdlClassRequired: 'Class A',
    endorsementsRequired: [],
    minExperienceYears: 1,
    payDescription: '$0.68 - $0.72 CPM + $2,500 Transition Bonus',
    avgWeeklyPay: 1850,
    operatingRegions: ['Midwest'],
    benefits: [
      'Guaranteed Home Every Weekend (Friday night to Monday morning)',
      '98% No-Touch Freight & 70% Drop & Hook',
      'Medical, Dental, Vision & Life Insurance',
      'EZ-Pass & PrePass equipped in every truck',
    ],
    status: 'active',
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'job-apex-local-homedaily',
    recruiterId: 'recruiter-apex-freight',
    companyName: 'Apex Freight Logistics',
    title: 'Local Home Daily Intermodal & Depot Shuttle',
    description: 'Daily yard jockey and rail ramp container shuttling in Indianapolis metro area. Work 5 days a week with consistent 10-hour shifts.',
    routeType: 'Local (Home Daily)',
    equipmentType: 'Intermodal / Container',
    cdlClassRequired: 'Class A',
    endorsementsRequired: ['TWIC Card'],
    minExperienceYears: 1,
    payDescription: '$29.50 - $33.00 / Hour + Overtime after 40 hrs',
    avgWeeklyPay: 1650,
    operatingRegions: ['Midwest'],
    benefits: [
      'Sleep in your own bed every single day',
      'Paid holidays and 2 weeks paid time off year 1',
      'Weekly payroll direct deposit',
    ],
    status: 'active',
    createdAt: '2026-08-16T14:00:00Z',
    updatedAt: '2026-08-16T14:00:00Z',
  },
];

export const SAMPLE_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-john-apex-reefer',
    jobId: 'job-apex-otr-reefer',
    jobTitle: 'OTR Reefer Dedicated Fleet Driver',
    companyName: 'Apex Freight Logistics',
    driverId: 'driver-john-reynolds',
    driverName: 'John "Mack" Reynolds',
    driverEmail: 'john.reynolds@trucklink.demo',
    driverPhone: '(555) 234-8901',
    driverCdlClass: 'Class A',
    driverExperience: 7,
    recruiterId: 'recruiter-apex-freight',
    status: 'interviewing',
    driverNote: 'Hi Sarah, I have 7 years of clean reefer experience and live right in Indianapolis. Looking forward to speaking about your dedicated routes.',
    recruiterNotes: 'Excellent credentials. Clean MVR and 7 years experience. Phone screen scheduled for tomorrow at 2:00 PM.',
    matchScore: 98,
    matchBreakdown: {
      cdlScore: 30,
      endorsementScore: 25,
      experienceScore: 20,
      equipmentScore: 15,
      routeScore: 10,
      reasons: ['Exact CDL Class A Match', 'Holds TWIC Card', '7 yrs experience (min 2 yrs)', 'Reefer specialization', 'OTR preference match'],
    },
    appliedAt: '2026-08-12T15:20:00Z',
    updatedAt: '2026-08-13T10:00:00Z',
    interviewDate: '2026-08-21T14:00:00Z',
  },
  {
    id: 'app-tyler-titan-tanker',
    jobId: 'job-titan-tanker-chemical',
    jobTitle: 'Specialty Chemical & Liquid Tanker Driver',
    companyName: 'Titan Liquid Bulk & Tank Lines',
    driverId: 'driver-tyler-vance',
    driverName: 'Tyler "Big Dog" Vance',
    driverEmail: 'tyler.vance@trucklink.demo',
    driverPhone: '(555) 345-6712',
    driverCdlClass: 'Class A',
    driverExperience: 10,
    recruiterId: 'recruiter-titan-tankers',
    status: 'offered',
    driverNote: 'Ready for immediate dispatch out of Texas terminal.',
    recruiterNotes: 'Top candidate. Sent formal employment offer letter at $0.88 CPM with $5k sign-on bonus.',
    matchScore: 100,
    matchBreakdown: {
      cdlScore: 30,
      endorsementScore: 25,
      experienceScore: 20,
      equipmentScore: 15,
      routeScore: 10,
      reasons: ['Exact CDL Class A Match', 'All HazMat/Tanker endorsements', '10 yrs experience', 'Tanker specialist'],
    },
    appliedAt: '2026-08-14T12:00:00Z',
    updatedAt: '2026-08-16T16:45:00Z',
  },
];
